$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$assetDirectory = $PSScriptRoot
$bitmap = [System.Drawing.Bitmap]::new(256, 256)
$graphics = [System.Drawing.Graphics]::FromImage($bitmap)
$graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
$graphics.Clear([System.Drawing.Color]::Transparent)
$green = [System.Drawing.SolidBrush]::new([System.Drawing.ColorTranslator]::FromHtml('#16795C'))
$mint = [System.Drawing.SolidBrush]::new([System.Drawing.ColorTranslator]::FromHtml('#E9F6E9'))
$white = [System.Drawing.Pen]::new([System.Drawing.Color]::White, 15)
$white.StartCap = [System.Drawing.Drawing2D.LineCap]::Round
$white.EndCap = [System.Drawing.Drawing2D.LineCap]::Round
$graphics.FillRectangle($green, 24, 16, 172, 218)
$graphics.FillRectangle($mint, 52, 55, 78, 10)
$graphics.FillRectangle($mint, 52, 80, 56, 10)
$graphics.DrawEllipse($white, 95, 102, 72, 72)
$graphics.DrawLine($white, 158, 164, 211, 216)
$bitmap.Save((Join-Path $assetDirectory 'RustSearch.png'), [System.Drawing.Imaging.ImageFormat]::Png)
$pngStream = [System.IO.MemoryStream]::new()
$bitmap.Save($pngStream, [System.Drawing.Imaging.ImageFormat]::Png)
$png = $pngStream.ToArray()
$iconStream = [System.IO.File]::Create((Join-Path $assetDirectory 'RustSearch.ico'))
$writer = [System.IO.BinaryWriter]::new($iconStream)
$writer.Write([uint16]0)
$writer.Write([uint16]1)
$writer.Write([uint16]1)
$writer.Write([byte]0)
$writer.Write([byte]0)
$writer.Write([byte]0)
$writer.Write([byte]0)
$writer.Write([uint16]1)
$writer.Write([uint16]32)
$writer.Write([uint32]$png.Length)
$writer.Write([uint32]22)
$writer.Write($png)
$writer.Dispose()
$pngStream.Dispose()
$white.Dispose()
$mint.Dispose()
$green.Dispose()
$graphics.Dispose()
$bitmap.Dispose()
